name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: actions/checkout@6.0.2
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run Tests
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Deploy Code
        run: echo "Deploying......"

